USE [master]
GO

/****** Object:  Database [AutoInfo]    Script Date: 12/19/2024 12:33:29 AM ******/
CREATE DATABASE [AutoInfo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AutoInfo', FILENAME = N'C:\Git\Notebook-Demo\AutoInfo.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AutoInfo_log', FILENAME = N'C:\Git\Notebook-Demo\AutoInfo_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AutoInfo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AutoInfo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AutoInfo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AutoInfo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AutoInfo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AutoInfo] SET ARITHABORT OFF 
GO

ALTER DATABASE [AutoInfo] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AutoInfo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AutoInfo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AutoInfo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AutoInfo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AutoInfo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AutoInfo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AutoInfo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AutoInfo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AutoInfo] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AutoInfo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AutoInfo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AutoInfo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AutoInfo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AutoInfo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AutoInfo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AutoInfo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AutoInfo] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AutoInfo] SET  MULTI_USER 
GO

ALTER DATABASE [AutoInfo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AutoInfo] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AutoInfo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AutoInfo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AutoInfo] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AutoInfo] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [AutoInfo] SET QUERY_STORE = OFF
GO

ALTER DATABASE [AutoInfo] SET  READ_WRITE 
GO

